<?php

    //include("_includes/config.inc");
    //include("_includes/dbconnect.inc");
    include("_includes/functions.inc");

    // Loads autoloader generated by Composer for Faker library
    require_once 'vendor/autoload.php';

    // Creates new instance of Faker library
    $faker = Faker\Factory::create();

    // Connects to database
    $db = new mysqli("localhost", "root", "", "cw2_students");

    // Drop IF EXISTS profile_picture
    //$db->query("ALTER TABLE IF EXISTS student DROP column IF EXISTS profile_picture");

    // Adds column into database for image files to be uploaded into
    //$db->query("ALTER TABLE student ADD COLUMN profile_picture BLOB");
    
    // Deletes all records from student table
    $db->query("DELETE FROM student");

    // Inserts predefined record for a student with ID 20000000
    $db->query("INSERT INTO student (studentid, password, dob, firstname, 
                lastname, house, town, county, country, postcode) 
                VALUES ('20000000', '$2y$10$.LJBOl64nZWEVVE/v5mgNuzR01zx1zoyXuGJUa/zp2U.MQxkps3LS', 
                '1974-11-10', 'Jon', 'Smith', '23 Victoria Road', 'High Wycombe', 
                'Bucks', 'UK', 'HP11 1RT');");

    // Resets auto-increment value
    $db->query("ALTER TABLE student AUTO_INCREMENT = 1");

    // Loops through range of students
    foreach(range(1,20) as $x)
    {
        $student_id = $x;

        $hashed_password = password_hash($_POST['password'], PASSWORD_DEFAULT);

        $date = mysqli_real_escape_string($db, $faker->date());
        $firstname = mysqli_real_escape_string($db, $faker->firstName());
        $lastname = mysqli_real_escape_string($db, $faker->lastname());
        $house = mysqli_real_escape_string($db, $faker->word());
        $town = mysqli_real_escape_string($db, $faker->city());
        $county = mysqli_real_escape_string($db, $faker->city());
        $country = mysqli_real_escape_string($db, $faker->country());
        $postcode = mysqli_real_escape_string($db, $faker->postcode());

        $sql = "
        INSERT INTO student (studentid, password, dob, firstname, 
        lastname, house, town, county, country, postcode)
        VALUES ('$student_id', '$hashed_password', 
        '{$date}', '{$firstname}', '{$lastname}', '{$house}', 
        '{$town}', '{$county}', '{$country}', '{$postcode}')";

        echo $sql . "<br />";

        // Inserts new record into student table using Faker generated data
        $db->query($sql);

        echo $student_id . "<br />";
    }
?>